server:
  port: 8080

music:
  data:
    path: ./music-data

app:
  jwt:
    secret: your-256-bit-secret-key-change-this-in-production-must-be-long
    expiration: 86400000
  admin:
    username: admin
    password: admin123

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: jdbc:sqlite:./music-data/musicplayer.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: ${AI_API_KEY} # 读取环境变量
      base-url: https://api.deepseek.com  # 请求地址指向 DeepSeek
      chat:
        options:
          model: deepseek-chat # 使用 DeepSeek V3 模型


#debug: true